services:
  docs:
    image: wrc_reporting_tool_local_docs
    container_name: wrc_reporting_tool_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./wrc_reporting_tool:/app/wrc_reporting_tool:z
    ports:
      - '9000:9000'
    command: /start-docs
